baseURL: "https://aaronappelle.github.io/" 
title: Aaron Appelle
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: "#research"
          weight: 1
        - name: More Info
          url: "#moreinfo"
          weight: 2

params:
    description: "This website hosts Aaron Appelle's research, curriculum vitae, and contact information."
    author: Aaron Appelle
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Aaron Appelle
          subtitle: "Hello! I am a final-year PhD candidate at Duke University advised by <a href=\"https://pratt.duke.edu/people/jerome-lynch/\" style=\"color:darkblue;\">Jerome Lynch</a>. My doctoral work focused on machine learning approaches to pedestrian and crowd modeling for location-based smart city services. My current research interests are in world models and video diffusion models for multi-agent simulation.<br><br>Recently, I was an AI resident at <a href=\"https://x.company/\" style=\"color:darkblue;\">Google X</a> working on generative models for architectural building design. Before my PhD, I completed a master's degree at Stanford University and bachelor's degree at Columbia University."
          imageUrl: "headshot.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: "#research"
            - name: More Info
              url: "#moreinfo"

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:aaron.appelle@duke.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=dNMxP3EAAAAJ&view_op=list_works&sortby=pubdate
        - name: GitHub
          url: https://github.com/aaronappelle
        # - name: Bluesky
        #   url: https://bsky.app/profile/newuser.bsky.social

    assets:
        disableScrollBarStyle: true
        favicon: "favicon.png"
        favicon16x16: "favicon.png"
        favicon32x32: "favicon.png"
        apple_touch_icon: "apple-touch-icon.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    
    # Show venue banners on research page thumbnails (only when summaries are shown)
    showVenueBanner: true
    
    # Show research summaries on /research page (when false, shows venue text instead)
    showResearchSummaries: true
    label:
      text: "Home"
      icon: favicon_aa.jpg
      iconHeight: 22

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2